[session_management_key]
secret_key = ""

[paths]
UPLOAD_FOLDER = "uploads"
top_wear_csv = "data/top_wear_clothing_attributes.csv"
bottom_wear_csv = "data/bottom_wear_clothing_attributes.csv"
users_csv = "data/users.csv"
clustering_weather_data_topwear = "data/clustering_weather_data_topwear.csv"
weather_suitability_model = "Models/weather_classification/weather_classifier_model.pkl"

[attribute_models]
model_path = "Models/attribute_models"

[geminiai]
api_key = ""
model = "gemini-2.5-flash"

[weather]
api_key = ""
